version: '3.8'

services:
  angular:
    build: 
      context: .
      dockerfile: ./VideoplayerApp/Dockerfile
    container_name: angular
    ports:
      - "4200:4200"
    volumes:
      - ./VideoplayerApp:/app

  database:
    image: "mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04"
    container_name: database
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa&&word2020"
    expose:
      - "1433"
    ports:
      - "1433:1433"
    volumes: ../sqldata:/var/opt/mssql/data
      
 
  webapi:
    build: 
      context: .
      dockerfile: ./SessionControl/Dockerfile 
    container_name: webapi
    expose: 
      - "443"
    ports:
      - "5000:80"
      - "5001:5001"

  worker:
    build: 
      context: .
      dockerfile: ./BackgroundWorker/Dockerfile
    container_name: worker
    enviroment:
      DBServer: "database"
    depends_on:
      - redis
      - database
    ports: 
      - "5100:5100"

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379" 
    volumes:
      - ./data:/data   
    