version: '3.8'

services:
  angular:
    image: "doc2210/internship_2210:vlatest"
    container_name: angular
    ports:
      - "4200:4200"
    depends_on: 
      - signalr

  database:
    image: "doc2210/mssql:sqlatest"
    restart: always
    container_name: database
    ports:
      - "1433:1433" 
    volumes: 
      - ./MSSQL/sqldata:/var/opt/mssql/data     
 
  webapi:
    image: "doc2210/web_api:slatest"
    container_name: webapi
    expose: 
      - "443"
    depends_on:
      - redis
      - database
      - rabbitmq
    ports:
      - "5000:80"
      - "5001:5001"

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379" 

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "8080:15672"
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password 

  signalr:
    image: "doc2210/signalr:latest" 
    container_name: signalr
    restart: on-failure
    depends_on:
      - rabbitmq
      - webapi
    ports:
      - "5002:80"
      - "5003:5003"

  hangfire:
    image: "doc2210/hangfire:latest"
    container_name: hangfire
    restart: on-failure
    depends_on:
      - redis
      - database

  hangfireclient: 
    image: "doc2210/hangfireclient:latest"
    container_name: hangfireclient
    restart: on-failure
    depends_on:
      - hangfire
      - redis
      - database
    ports:
      - "5004:80"
      - "5005:5005"
  
    